services:
  postgres:
    container_name: nest_course
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - nestjs-course

volumes:
  postgres_data:

networks:
  nestjs-course: